@api_url = http://localhost:5000/
//@api_url = https://design-patterns-55320.azurewebsites.net/

### Get all subjects
GET {{api_url}}

### Get subject by ID
GET {{api_url}}/6
Accept-Language: pl

### Create subject
POST {{api_url}} HTTP/1.1
Content-Type: application/json

{
    "name": "Systemy autonomiczne"
}

### Delete subject
DELETE {{api_url}}/4 HTTP/1.1
Accept-Language: de
